server:
  port: 8000
spring:
  application:
    name: "ticket"
  mvc:
    locale-resolver: fixed
    locate: pt_BR
  datasource:
    url: jdbc:mysql://localhost:3308/ticket_prod?useTimezone=true&serverTimezone=UTC
    username: docker
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  sql:
    init:
      mode: always
