server:
  port: 8000
spring:
  application:
    name: "ticket"
  mvc:
    locale-resolver: fixed
    locate: pt_BR
  datasource:
    url: jdbc:mysql://localhost:3308/ticket_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  sql:
    init:
      mode: always
